; Default hotkey table for the mini edition.
; User overrides from [Keys] are loaded first, then missing keys are filled below.

KeysInit() {
    global keyset, CLSets
    keyset := Map()

    if CLSets.Has("Keys") {
        for keyName, funcSpec in CLSets["Keys"]
            keyset[NormalizeSettingKey(keyName)] := funcSpec
    }

    KeySchemeInit_capslox()
}

KeySchemeInit_capslox() {
    defaults := [
        ["press_caps", "keyFunc_toggleCapsLock"],
        ["caps_a", "keyFunc_moveWordLeft"],
        ["caps_b", "keyFunc_moveDown(10)"],
        ["caps_c", "keyFunc_copy_1"],
        ["caps_d", "keyFunc_moveDown"],
        ["caps_e", "keyFunc_moveUp"],
        ["caps_f", "keyFunc_moveRight"],
        ["caps_g", "keyFunc_moveWordRight"],
        ["caps_h", "keyFunc_selectWordLeft"],
        ["caps_i", "keyFunc_selectUp"],
        ["caps_j", "keyFunc_selectLeft"],
        ["caps_k", "keyFunc_selectDown"],
        ["caps_l", "keyFunc_selectRight"],
        ["caps_m", "keyFunc_doNothing"],
        ["caps_n", "keyFunc_selectDown(10)"],
        ["caps_o", "keyFunc_selectEnd"],
        ["caps_p", "keyFunc_home"],
        ["caps_q", "keyFunc_doNothing"],
        ["caps_r", "keyFunc_delete"],
        ["caps_s", "keyFunc_moveLeft"],
        ["caps_t", "keyFunc_moveUp(10)"],
        ["caps_u", "keyFunc_selectHome"],
        ["caps_v", "keyFunc_paste_1"],
        ["caps_w", "keyFunc_backspace"],
        ["caps_x", "keyFunc_cut_1"],
        ["caps_y", "keyFunc_selectUp(10)"],
        ["caps_z", "keyFunc_doNothing"],
        ["caps_backquote", "keyFunc_doNothing"],
        ["caps_1", "keyFunc_winbind_activate(1)"],
        ["caps_2", "keyFunc_winbind_activate(2)"],
        ["caps_3", "keyFunc_winbind_activate(3)"],
        ["caps_4", "keyFunc_winbind_activate(4)"],
        ["caps_5", "keyFunc_winbind_activate(5)"],
        ["caps_6", "keyFunc_winbind_activate(6)"],
        ["caps_7", "keyFunc_winbind_activate(7)"],
        ["caps_8", "keyFunc_winbind_activate(8)"],
        ["caps_9", "keyFunc_winbind_activate(9)"],
        ["caps_0", "keyFunc_winbind_activate(10)"],
        ["caps_minus", "keyFunc_doNothing"],
        ["caps_equal", "keyFunc_doNothing"],
        ["caps_backspace", "keyFunc_deleteLine"],
        ["caps_tab", "keyFunc_doNothing"],
        ["caps_leftsquarebracket", "keyFunc_deleteToLineBeginning"],
        ["caps_rightsquarebracket", "keyFunc_doNothing"],
        ["caps_backslash", "keyFunc_doNothing"],
        ["caps_semicolon", "keyFunc_end"],
        ["caps_quote", "keyFunc_doNothing"],
        ["caps_enter", "keyFunc_enterWherever"],
        ["caps_comma", "keyFunc_selectCurrentWord"],
        ["caps_dot", "keyFunc_selectWordRight"],
        ["caps_slash", "keyFunc_deleteToLineEnd"],
        ["caps_space", "keyFunc_enter"],
        ["caps_ralt", "keyFunc_doNothing"],
        ["caps_f1", "keyFunc_openCpasDocs"],
        ["caps_f2", "keyFunc_doNothing"],
        ["caps_f3", "keyFunc_doNothing"],
        ["caps_f4", "keyFunc_winTransparent"],
        ["caps_f5", "keyFunc_reload"],
        ["caps_f6", "keyFunc_winPin"],
        ["caps_f7", "keyFunc_doNothing"],
        ["caps_f8", "keyFunc_doNothing"],
        ["caps_f9", "keyFunc_doNothing"],
        ["caps_f10", "keyFunc_doNothing"],
        ["caps_f11", "keyFunc_doNothing"],
        ["caps_f12", "keyFunc_doNothing"],
        ["caps_lalt_a", "keyFunc_moveWordLeft(3)"],
        ["caps_lalt_b", "keyFunc_moveDown(30)"],
        ["caps_lalt_c", "keyFunc_copy_2"],
        ["caps_lalt_d", "keyFunc_moveDown(3)"],
        ["caps_lalt_e", "keyFunc_moveUp(3)"],
        ["caps_lalt_f", "keyFunc_moveRight(5)"],
        ["caps_lalt_g", "keyFunc_moveWordRight(3)"],
        ["caps_lalt_h", "keyFunc_selectWordLeft(3)"],
        ["caps_lalt_i", "keyFunc_selectUp(3)"],
        ["caps_lalt_j", "keyFunc_selectLeft(5)"],
        ["caps_lalt_k", "keyFunc_selectDown(3)"],
        ["caps_lalt_l", "keyFunc_selectRight(5)"],
        ["caps_lalt_m", "keyFunc_doNothing"],
        ["caps_lalt_n", "keyFunc_selectDown(30)"],
        ["caps_lalt_o", "keyFunc_selectToPageEnd"],
        ["caps_lalt_p", "keyFunc_moveToPageBeginning"],
        ["caps_lalt_q", "keyFunc_doNothing"],
        ["caps_lalt_r", "keyFunc_forwardDeleteWord"],
        ["caps_lalt_s", "keyFunc_moveLeft(5)"],
        ["caps_lalt_t", "keyFunc_moveUp(30)"],
        ["caps_lalt_u", "keyFunc_selectToPageBeginning"],
        ["caps_lalt_v", "keyFunc_paste_2"],
        ["caps_lalt_w", "keyFunc_deleteWord"],
        ["caps_lalt_x", "keyFunc_cut_2"],
        ["caps_lalt_y", "keyFunc_selectUp(30)"],
        ["caps_lalt_z", "keyFunc_doNothing"],
        ["caps_lalt_backquote", "keyFunc_doNothing"],
        ["caps_lalt_1", "keyFunc_winbind_binding(1)"],
        ["caps_lalt_2", "keyFunc_winbind_binding(2)"],
        ["caps_lalt_3", "keyFunc_winbind_binding(3)"],
        ["caps_lalt_4", "keyFunc_winbind_binding(4)"],
        ["caps_lalt_5", "keyFunc_winbind_binding(5)"],
        ["caps_lalt_6", "keyFunc_winbind_binding(6)"],
        ["caps_lalt_7", "keyFunc_winbind_binding(7)"],
        ["caps_lalt_8", "keyFunc_winbind_binding(8)"],
        ["caps_lalt_9", "keyFunc_winbind_binding(9)"],
        ["caps_lalt_0", "keyFunc_winbind_binding(10)"],
        ["caps_lalt_minus", "keyFunc_doNothing"],
        ["caps_lalt_equal", "keyFunc_doNothing"],
        ["caps_lalt_backspace", "keyFunc_deleteAll"],
        ["caps_lalt_tab", "keyFunc_doNothing"],
        ["caps_lalt_leftsquarebracket", "keyFunc_deleteToPageBeginning"],
        ["caps_lalt_rightsquarebracket", "keyFunc_doNothing"],
        ["caps_lalt_backslash", "keyFunc_doNothing"],
        ["caps_lalt_semicolon", "keyFunc_moveToPageEnd"],
        ["caps_lalt_quote", "keyFunc_doNothing"],
        ["caps_lalt_enter", "keyFunc_doNothing"],
        ["caps_lalt_comma", "keyFunc_selectCurrentLine"],
        ["caps_lalt_dot", "keyFunc_selectWordRight(3)"],
        ["caps_lalt_slash", "keyFunc_deleteToPageEnd"],
        ["caps_lalt_space", "keyFunc_doNothing"],
        ["caps_lalt_ralt", "keyFunc_doNothing"],
        ["caps_win_1", "keyFunc_winbind_binding(1)"],
        ["caps_win_2", "keyFunc_winbind_binding(2)"],
        ["caps_win_3", "keyFunc_winbind_binding(3)"],
        ["caps_win_4", "keyFunc_winbind_binding(4)"],
        ["caps_win_5", "keyFunc_winbind_binding(5)"],
        ["caps_win_6", "keyFunc_winbind_binding(6)"],
        ["caps_win_7", "keyFunc_winbind_binding(7)"],
        ["caps_win_8", "keyFunc_winbind_binding(8)"],
        ["caps_win_9", "keyFunc_winbind_binding(9)"],
        ["caps_win_0", "keyFunc_winbind_binding(10)"]
    ]

    for item in defaults
        SetDefaultKey(item[1], item[2])
}
